<?xml version="1.0"?>
<robot name="flexible_cable" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="blue_color" value="0 0 0.8 1" />
  <xacro:property name="red_color" value="1 0 0 1" />
  <xacro:property name="gray_color" value="0.5 0.5 0.5 1" />
  <xacro:property name="sphere_radius" value="0.003" />
  <xacro:property name="cylinder_radius" value="0.003" />
  <xacro:property name="cylinder_length" value="0.01" />
  <xacro:property name="cable_height" value="2" />
  <xacro:property name="damping" value="0.1" />
  <xacro:property name="friction" value="0.0" />

  <material name="blue">
    <color rgba="${blue_color}"/>
  </material>

  <material name="gray">
    <color rgba="${gray_color}"/>
  </material>

  <!-- World link (invisible) -->
  <link name="world"/>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${4 * cylinder_length} ${4 * cylinder_length} ${2 * cylinder_length}"/>
      </geometry>
      <material name="red">
        <color rgba="${red_color}"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${4 * cylinder_length} ${4 * cylinder_length} ${2 * cylinder_length}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <gazebo reference="base_link">
    <material>Gazebo/Gray</material>
    <selfCollide>true</selfCollide>
  </gazebo>

  <!-- Fixed joint to connect base_link to world -->
  <joint name="fixed_to_world" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${cable_height}" rpy="1.57 0 0"/>
  </joint>

  <!-- Cable segment macro -->
  <xacro:macro name="cable_segment" params="name parent">
    <!-- Spherical joint -->
    <link name="${name}_sphere">
      <visual>
        <geometry>
          <sphere radius="${sphere_radius}"/>
        </geometry>
        <material name="gray"/>
      </visual>
      <collision>
        <geometry>
          <sphere radius="${sphere_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <mass value="0.005"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>
    </link>

  <joint name="${parent}_to_${name}_sphere" type="revolute">
    <parent link="${parent}"/>
    <child link="${name}_sphere"/>
    <origin xyz="0 0 ${-cylinder_length - 2 * sphere_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-3.14" upper="3.14" effort="10" velocity="3"/>
    <dynamics damping="${damping}" friction="${friction}"/>
  </joint>

    <!-- Cylinder segment -->
  <link name="${name}_cylinder">
    <visual>
      <geometry>
        <cylinder length="${cylinder_length}" radius="${cylinder_radius}"/>
      </geometry>
      <origin xyz="0 0 ${-cylinder_length/2- sphere_radius}" rpy="0 0 0"/>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${cylinder_length}" radius="${cylinder_radius}"/>
      </geometry>
      <origin xyz="0 0 ${-cylinder_length/2- sphere_radius}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      <origin xyz="0 0 ${-cylinder_length/2- sphere_radius}" rpy="0 0 0"/>
    </inertial>
  </link>

  <joint name="${name}_sphere_to_cylinder" type="revolute">
    <parent link="${name}_sphere"/>
    <child link="${name}_cylinder"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="-3.14" upper="3.14" effort="10" velocity="3"/>
    <dynamics damping="${damping}" friction="${friction}"/>
  </joint>

    <!-- Enable self-collision for this segment -->
  <gazebo reference="${name}_sphere">
    <material>Gazebo/Gray</material>
    <selfCollide>true</selfCollide>
  </gazebo>

  <gazebo reference="${name}_cylinder">
    <material>Gazebo/Blue</material>
    <selfCollide>true</selfCollide>
  </gazebo>
  </xacro:macro>

  <!-- Create 50 segments -->
  <xacro:cable_segment name="segment_1" parent="base_link"/>
  <xacro:cable_segment name="segment_2" parent="segment_1_cylinder"/>
  <xacro:cable_segment name="segment_3" parent="segment_2_cylinder"/>
  <xacro:cable_segment name="segment_4" parent="segment_3_cylinder"/>
  <xacro:cable_segment name="segment_5" parent="segment_4_cylinder"/>
  <xacro:cable_segment name="segment_6" parent="segment_5_cylinder"/>
  <xacro:cable_segment name="segment_7" parent="segment_6_cylinder"/>
  <xacro:cable_segment name="segment_8" parent="segment_7_cylinder"/>
  <xacro:cable_segment name="segment_9" parent="segment_8_cylinder"/>
  <xacro:cable_segment name="segment_10" parent="segment_9_cylinder"/>
  <xacro:cable_segment name="segment_11" parent="segment_10_cylinder"/>
  <xacro:cable_segment name="segment_12" parent="segment_11_cylinder"/>
  <xacro:cable_segment name="segment_13" parent="segment_12_cylinder"/>
  <xacro:cable_segment name="segment_14" parent="segment_13_cylinder"/>
  <xacro:cable_segment name="segment_15" parent="segment_14_cylinder"/>
  <xacro:cable_segment name="segment_16" parent="segment_15_cylinder"/>
  <xacro:cable_segment name="segment_17" parent="segment_16_cylinder"/>
  <xacro:cable_segment name="segment_18" parent="segment_17_cylinder"/>
  <xacro:cable_segment name="segment_19" parent="segment_18_cylinder"/>
  <xacro:cable_segment name="segment_20" parent="segment_19_cylinder"/>
  <xacro:cable_segment name="segment_21" parent="segment_20_cylinder"/>
  <xacro:cable_segment name="segment_22" parent="segment_21_cylinder"/>
  <xacro:cable_segment name="segment_23" parent="segment_22_cylinder"/>
  <xacro:cable_segment name="segment_24" parent="segment_23_cylinder"/>
  <xacro:cable_segment name="segment_25" parent="segment_24_cylinder"/>
  <xacro:cable_segment name="segment_26" parent="segment_25_cylinder"/>
  <xacro:cable_segment name="segment_27" parent="segment_26_cylinder"/>
  <xacro:cable_segment name="segment_28" parent="segment_27_cylinder"/>
  <xacro:cable_segment name="segment_29" parent="segment_28_cylinder"/>
  <xacro:cable_segment name="segment_30" parent="segment_29_cylinder"/>
  <xacro:cable_segment name="segment_31" parent="segment_30_cylinder"/>
  <xacro:cable_segment name="segment_32" parent="segment_31_cylinder"/>
  <xacro:cable_segment name="segment_33" parent="segment_32_cylinder"/>
  <xacro:cable_segment name="segment_34" parent="segment_33_cylinder"/>
  <xacro:cable_segment name="segment_35" parent="segment_34_cylinder"/>
  <xacro:cable_segment name="segment_36" parent="segment_35_cylinder"/>
  <xacro:cable_segment name="segment_37" parent="segment_36_cylinder"/>
  <xacro:cable_segment name="segment_38" parent="segment_37_cylinder"/>
  <xacro:cable_segment name="segment_39" parent="segment_38_cylinder"/>
  <xacro:cable_segment name="segment_40" parent="segment_39_cylinder"/>
  <xacro:cable_segment name="segment_41" parent="segment_40_cylinder"/>
  <xacro:cable_segment name="segment_42" parent="segment_41_cylinder"/>
  <xacro:cable_segment name="segment_43" parent="segment_42_cylinder"/>
  <xacro:cable_segment name="segment_44" parent="segment_43_cylinder"/>
  <xacro:cable_segment name="segment_45" parent="segment_44_cylinder"/>
  <xacro:cable_segment name="segment_46" parent="segment_45_cylinder"/>
  <xacro:cable_segment name="segment_47" parent="segment_46_cylinder"/>
  <xacro:cable_segment name="segment_48" parent="segment_47_cylinder"/>
  <xacro:cable_segment name="segment_49" parent="segment_48_cylinder"/>
  <xacro:cable_segment name="segment_50" parent="segment_49_cylinder"/>




  <!-- add one sphere at the end -->
  <link name="end_sphere">
    <visual>
      <geometry>
        <sphere radius="${sphere_radius}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${sphere_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.005"/>
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="joint_end_sphere" type="revolute">
    <parent link="segment_50_cylinder"/>
    <child link="end_sphere"/>
    <origin xyz="0 0 ${-cylinder_length - 2 * sphere_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="3"/>
    <dynamics damping="${damping}" friction="${friction}"/>
  </joint>

  <gazebo>

    <plugin name="cable_vel_control_plugin" filename="libcable_vel_control_plugin.so">
      <!-- <ros_topic>/target_position</ros_topic> -->
      <link_name>end_sphere</link_name>
    </plugin>



    <self_collide>true</self_collide>
    <!-- <static>true</static> -->
  </gazebo>


</robot>